---
title: "R Notebook"
author: "Hernan Lorenzi"
output:
  html_document:
    df_print: paged
---

# Load libraries
```{r}
library(tidyverse)
library(DESeq2)
library(cowplot)
library(ggpubr)
library("RColorBrewer")
library(pheatmap)
library(ggsci)
```

# Load data
```{r}
read_counts <- as.data.frame(read_tsv(file = "05counts/read_counts", col_names = TRUE, comment = "#"))
rownames(read_counts) <- read_counts$Geneid # adding gene ids as row names
read_counts <- read_counts[, c(7:10)] # Keeping just the reads count columns

# Rename sample names
colnames(read_counts) <- c("SRR3419767", "SRR3419770", "SRR3419769", "SRR3419768")

# Build metadata table
metadata <- as.data.frame(cbind(
  sample_id = c("testes_1", "testes_2", "seminal_vesicles_1", "seminal_vesicles_2"),
  tissue = c(rep("testes",2), rep("seminal_vesicles",2)),
  sra_id =c("SRR3419767","SRR3419768","SRR3419769","SRR3419770")
                   )
              )
rownames(metadata) <- metadata$sra_id
metadata$tissue <- as.factor(metadata$tissue)

# Sort tables so metadata and read counts match order
read_counts <- read_counts[,match(rownames(metadata), colnames(read_counts))]

# Round read counts to the closest interger
read_counts <- round(read_counts, digits = 0)

# include total read counts in metadata
metadata$read_counts <- colSums(read_counts)
```

# DE analysis with DESeq2
```{r}
dir.create(path = "./Plots", showWarnings = FALSE)

# Adding read_depth in design to control for read_depth
dds.gse80548 <- DESeqDataSetFromMatrix(countData = read_counts, 
                              colData = metadata,  
                              design = ~ tissue)


# Plot total reads per sample using barchar
p <- ggbarplot(data = metadata, 
          x = "sample_id", 
          y = "read_counts",
          x.text.angle = 90,
          fill = "tissue", 
          title = "Total read counts per sample", 
          ylab = "Read counts",
          sort.by.groups = TRUE,
          palette = "jco",
          sort.val = "asc")

ggsave2("Plots/barplot_read_counts_per_sample.pdf", plot = p)

# Normalize counts
vsd.gse80548 <- vst(dds.gse80548, blind=FALSE)

# Keep genes with at least 20 reads total across samples
keep <- rowSums(as.data.frame(vsd.gse80548@assays@data@listData)) >= 20
vsd.gse80548 <- vsd.gse80548[keep,]

# Calculate distances between samples
sampleDists <- dist(t(assay(vsd.gse80548)))

# Plot inter-sample distances
old.par <- par(no.readonly=T)

sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- paste(vsd.gse80548$tissue)
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
p.hm <- pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors)

ggsave2(filename = "./Plots/heat_map.pdf", plot = p.hm)
p.hm

# PCA
pcaData <- plotPCA(vsd.gse80548, intgroup=c("tissue"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
y.coords = c(min(pcaData$PC1, pcaData$PC2), max(pcaData$PC1, pcaData$PC2))
x.coords = y.coords
p1 <- ggplot(pcaData, aes(PC1, PC2, color=tissue)) +
  geom_point(size=3) + scale_color_lancet() + 
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed(ratio = (max(pcaData$PC1)-min(pcaData$PC1))/(max(pcaData$PC2)-min(pcaData$PC2))) 

ggsave("Plots/pca_by_tissue.pdf", plot = p1)
p1

```
# Run DE analysis
```{r}

dir.create(path = "./DE", showWarnings = FALSE)

# Calculate DE for WT samples
dds.gse80548$Group_gt_ind <- relevel(dds.gse80548$tissue, "seminal_vesicles")
dds.gse80548 <- DESeq(dds.gse80548)
resultsNames(dds.gse80548)


# Using lfcShrink instead of results to reduce high Log2FC bias of genes with low expression
res_testes_vs_sem_ves <- lfcShrink(dds.gse80548, coef = "tissue_testes_vs_seminal_vesicles", type = "ashr", )

# Replace NAs by 1s
res_testes_vs_sem_ves$pvalue[is.na(res_testes_vs_sem_ves$pvalue)] <- 1
res_testes_vs_sem_ves$padj[is.na(res_testes_vs_sem_ves$padj)] <- 1

summary(res_testes_vs_sem_ves, alpha = 0.05)

# Save DE results
write.table(x = as.data.frame(res_testes_vs_sem_ves), file = "./DE/DE_testes_vs_sem_ves.txt", sep = "\t")

```
